### ISSUE TITLE
Downloading vendor list fails

### ISSUE THREAD

**Issue by JoeTester1965** [bauerj/mac_vendor_lookup#3]
Hi,

Using this for python3 in Microsoft Visual Studio, get this warning which (am not a Python expert) I do not understand. any ideas:

raceback (most recent call last):
  File "F:\Derek\Source\Repos\WiFiProcessing\WiFiProcessing\WiFiProcessing.py", line 67, in <module>
    main()
  File "F:\Derek\Source\Repos\WiFiProcessing\WiFiProcessing\WiFiProcessing.py", line 58, in main
    find_mac("00:80:41:12:FE");
  File "F:\Derek\Source\Repos\WiFiProcessing\WiFiProcessing\WiFiProcessing.py", line 9, in find_mac
    print(mac.lookup(mac_address))  # <- this will only take a few µs!
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mac_vendor_lookup.py", line 84, in lookup
    return self.loop.run_until_complete(self.async_lookup.lookup(mac))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mac_vendor_lookup.py", line 72, in lookup
    return self.prefixes[mac[:6]].decode("utf8")
KeyError: b'008041'
Press any key to continue . . .

**Comment by bauerj** [comment]
Hey Derek,

thanks for reporting this. I just checked and was unable to reproduce the issue you see:

```PS C:\Users\bauerj> python3
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mac_vendor_lookup import MacLookup
>>> print(MacLookup().lookup("00:80:41:12:FE"))
VEB KOMBINAT ROBOTRON
```

Can you show the code you are using?

Also, can you check the size of the file `%AppData%\..\..\.cache\mac-vendors.txt`?

**Comment by JoeTester1965** [comment]
Hi, thanks for the response

Vendors file is 160KB

Have minimised code that reproduces issue:

from mac_vendor_lookup import MacLookup

mac = MacLookup()
mac.load_vendors() 

def find_mac(mac_address):
    print(mac.lookup(mac_address)) 

filename_csv="test.csv"

def main():

    find_mac("00:80:41:12:FE");
      
if __name__ == '__main__':
    main()

->

Traceback (most recent call last):
  File "F:\Derek\Source\Repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 16, in <module>
    main()
  File "F:\Derek\Source\Repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 13, in main
    find_mac("00:80:41:12:FE");
  File "F:\Derek\Source\Repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 7, in find_mac
    print(mac.lookup(mac_address))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mac_vendor_lookup.py", line 84, in lookup
    return self.loop.run_until_complete(self.async_lookup.lookup(mac))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mac_vendor_lookup.py", line 72, in lookup
    return self.prefixes[mac[:6]].decode("utf8")
KeyError: b'008041'

**Comment by bauerj** [comment]
160kB is too small, it should be 800kB. Please delete the file and try again.

If that fixes the issue I will add code that checks if the download was successful before opening the file. Did you see an error message while downloading?

**Comment by JoeTester1965** [comment]
Thanks, that was what happened, all well.

I did not see any errors other than what was posted.

Thank you.

**Comment by tuanjggaa** [comment]
Hi @bauerj ! I got the same issue as him! Luckily my laptop is able to download the fill file which was 806kB, but my PC couldn't. 
Everytime i tried to download the file from PC, the file's size is too small (200-300-421-123kB) can't get the full fill. So i have to copy the file from my laptop to my PC, everything work great.
I Hope you can fix the issue, My Laptop is using Intel, and my PC is using Intel
Thanks!

**Comment by bauerj** [comment]
Hey, 

I will try and add the current file to the package so it comes pre-installed.

However, I'm still a bit confused about why this is happening. Can you run the following code on your PC to see if it shows some error message?

```python
from mac_vendor_lookup import MacLookup

MacLookup().load_vendors()
```

**Comment by tuanjggaa** [comment]
Oh! It just downloaded the whole file 806KB(Run on cmd).
When i Run it on pycharm its has the error:
AttributeError: 'MacLookup' object has no attribute 'load_vendors'
Also if i don't load the whole MAC list first from pycharm but search for the MAC, the file won't be at full size. 
Thanks!

**Comment by bauerj** [comment]
Hey @tuanjggaa,

the library distribution now contains the list. Could you please test if that works for you?

**Comment by bauerj** [comment]
I assume this works now, if not please let me know.
